# Generated by Django 3.0 on 2022-01-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_auto_20220104_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='registrador_por',
            new_name='registrado_por',
        ),
    ]
